import { Request, Response } from 'express';
import { prisma } from '../config/database.js';
import { successResponse, errorResponse } from '../utils/apiResponse.js';

// GET approved comments for a blog post slug
export async function handleGetCommentsByBlogSlug(req: Request, res: Response) {
  try {
    const { slug } = req.params;

    // Find the blog first to get its ID
    const blog = await prisma.blog.findUnique({
      where: { slug },
    });

    if (!blog) {
      return successResponse(res, { data: [] });
    }

    const comments = await prisma.comment.findMany({
      where: {
        blogId: blog.id,
        approved: true,
      },
      orderBy: {
        createdAt: 'desc',
      },
      select: {
        id: true,
        blogId: true,
        name: true,
        content: true,
        createdAt: true,
      },
    });

    return successResponse(res, { data: comments });
  } catch (err: any) {
    return errorResponse(res, err.message || 'Failed to fetch comments.', 500);
  }
}

// POST a new comment
export async function handleAddCommentByBlogSlug(req: Request, res: Response) {
  try {
    const { slug } = req.params;
    const { name, email, content } = req.body;

    if (!name || !email || !content) {
      return errorResponse(res, 'Missing required fields (name, email, content).', 400);
    }

    // Find the blog post
    let blog = await prisma.blog.findUnique({
      where: { slug },
    });

    // Fallback logic in case the database blog table isn't fully seeded yet
    if (!blog) {
      // Create a shell for the blog post using generic info
      // Title and other info will be populated in subsequent syncs
      blog = await prisma.blog.create({
        data: {
          title: slug.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
          slug,
          excerpt: 'Autogenerated post shell for user discussions.',
          content: 'No content available yet.',
          published: true,
          publishedAt: new Date(),
        },
      });
    }

    const newComment = await prisma.comment.create({
      data: {
        blogId: blog.id,
        name,
        email,
        content,
        approved: true, // Defaulting to true
      },
      select: {
        id: true,
        blogId: true,
        name: true,
        content: true,
        createdAt: true,
      },
    });

    return successResponse(res, { data: newComment });
  } catch (err: any) {
    return errorResponse(res, err.message || 'Failed to add comment.', 500);
  }
}
